### ISSUE TITLE
Unable to process large dataset

### ISSUE THREAD

**Issue by prabhakar267** [facebookresearch/muss#10]
I'm trying to run the simplify script on WMT14 dataset. After 2 days of processing, the script failed with the following error. Any fixes?

I do not get any errors when running on a smaller dataset.

```
Traceback (most recent call last):
  File "scripts/simplify.py", line 28, in <module>
    pred_sentences = simplify_sentences(source_sentences, model_name=args.model_name)
  File ".../muss/simplify.py", line 76, in simplify_sentences
    pred_path = simplifier(source_path)
  File ".../muss/simplifiers.py", line 42, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File ".../muss/simplifiers.py", line 30, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File ".../muss/simplifiers.py", line 68, in preprocessed_simplifier
    preprocessed_pred_filepath = simplifier(preprocessed_complex_filepath)
  File ".../muss/simplifiers.py", line 42, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File ".../muss/simplifiers.py", line 30, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File ".../muss/simplifiers.py", line 54, in fairseq_simplifier
    fairseq_generate(complex_filepath, output_pred_filepath, exp_dir, **kwargs)
  File ".../muss/fairseq/base.py", line 235, in fairseq_generate
    **kwargs,
  File ".../muss/utils/training.py", line 60, in wrapped_func
    return func(*args, **kwargs)
  File ".../muss/fairseq/base.py", line 191, in _fairseq_generate
    predictions = [hypotheses[hypothesis_num - 1] for hypotheses in all_hypotheses]
  File ".../muss/fairseq/base.py", line 191, in <listcomp>
    predictions = [hypotheses[hypothesis_num - 1] for hypotheses in all_hypotheses]
IndexError: list index out of range
```

**Comment by louismartin** [comment]
Hi,

Thanks for raising this issue. I'm not sure what's the problem exactly, but maybe you should split your dataset into smaller files and process them separately.
I never tested the simplified script on large files.
I'm closing this issue for now, but feel free to reopen or to comment if you have further issues
