### ISSUE TITLE
There appear to be 1 leaked folder objects to clean up at shutdown

### ISSUE THREAD

**Issue by AssisRaphael** [facebookresearch/muss#37]
Hello,

I'm trying to replicate your work for the portuguese language. I made some small adjustments to the code and I'm trying to run the sentence mining phase. However, I'm running into the following error:

```shell
raphael@instance-1:~/muss-ptBR$ cat nohup.out 
/home/raphael/.local/lib/python3.8/site-packages/submitit/core/core.py:718: RuntimeWarning: No submission happened during "with executor.batch()" context.
  warnings.warn(
Splitting CCNet shards into smaller subshards...
[]
0it [00:00, ?it/s]
Splitting CCNet shards into smaller subshards completed after 0.09s.
Tokenizing sentences...
[]
0it [00:00, ?it/s]/home/raphael/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:310: UserWarning: resource_tracker: There appear to be 6 leaked semlock objects to clean up at shutdown
  warnings.warn(
/home/raphael/.local/lib/python3.8/site-packages/joblib/externals/loky/backend/resource_tracker.py:310: UserWarning: resource_tracker: There appear to be 1 leaked folder objects to clean up at shutdown
  warnings.warn(
[1]+  Killed                  nohup python3 scripts/mine_sequences.py
```

At this first moment I'm trying to understand how the code works. I'm running with only 1 shard mined from cc_net and on a machine with 1 TESLA T4 GPU, 8vCPUs and 85GB of RAM. As I understand it is not a hardware problem (more than 50% of the memory was not used) and there are no problems in the process logs. I'm analyzing if it's a problem with the python version I'm using (3.8). Do you have any idea what this error could be?

**Comment by louismartin** [comment]
Hi @AssisRaphael , great to hear that you are trying to run simplification for portuguese.

## Related to your error
It looks like the script is not processing anything, can you double check that it actually found your shard and is doing anything with it?
```
/home/raphael/.local/lib/python3.8/site-packages/submitit/core/core.py:718: RuntimeWarning: No submission happened during "with executor.batch()" context.
  warnings.warn(
Splitting CCNet shards into smaller subshards...
[]
0it [00:00, ?it/s]
Splitting CCNet shards into smaller subshards completed after 0.09s.
```

I am not sure where the error comes from, but my guess is that the `leaked folder objects to clean up at shutdown` is not the cause of the error but rather a consequence. I.e. there is an obscure silent error first and then the warning are thrown when python tries to exit.

PS: If you manage to successfully mine sentences and train your model for Portuguese, would you mind writing down some quick experiment logs in a markdown file detailing what you tried? I think it could be really useful for others trying to do the same with other languages.
Things that would be especially useful are bugs that you had and how you solved them, time it took to run the sentence mining and training and the hardware you used, tips that you got along the way ...

**Comment by AssisRaphael** [comment]
Hello again @louismartin ,

I was able to work around the previous problem by reducing the number of documents per file (n_docs_per_file) in the sharding phase. However, now I'm having another problem in the computing embeddings phase. I imagine that this is another silent error, because in the logs it appears that the GPU memory overflows, but looking at the graphics, the GPU utilization doesn't even reach 80% of use. My current logs are as follows:

```shell
Splitting CCNet shards into smaller subshards...
['2360']

  0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:11<00:00, 11.01s/it]
100%|██████████| 1/1 [00:11<00:00, 11.01s/it]
Splitting CCNet shards into smaller subshards completed after 11.16s.
Tokenizing sentences...
['2396', '2407', '2411', '2421', '2432', '2443', '2454', '2475', '2486', '2490', '2509', '2537', '2556', '2559', '2579', '2591', '2604', '2614', '2634', '2647', '2656', '2664']

  0%|          | 0/22 [00:00<?, ?it/s]
  5%|▍         | 1/22 [00:27<09:27, 27.03s/it]
  9%|▉         | 2/22 [00:32<04:41, 14.07s/it]
 18%|█▊        | 4/22 [00:35<01:51,  6.19s/it]
 23%|██▎       | 5/22 [00:36<01:17,  4.59s/it]
 27%|██▋       | 6/22 [00:39<01:05,  4.10s/it]
 41%|████      | 9/22 [00:42<00:30,  2.34s/it]
 68%|██████▊   | 15/22 [00:44<00:07,  1.10s/it]
 73%|███████▎  | 16/22 [00:45<00:06,  1.09s/it]
100%|██████████| 22/22 [00:45<00:00,  2.05s/it]
Tokenizing sentences completed after 49.75s.
Creating base index...
Expected index size: 512.0GB
Computing embeddings...
Computing embeddings completed after 1572.59s.
Training index...
Training index completed after 1239.34s.
Creating base index completed after 2813.80s.
Computing embeddings...
['9480', '9491', '9502', '9513', '9533', '9543', '9554', '9559', '9596', '9599', '9618', '9629', '9635', '9665', '9703', '9770', '9807', '9830', '9899', '9948', '10005', '10064']

  0%|          | 0/22 [00:00<?, ?it/s]
  5%|▍         | 1/22 [20:37<7:13:03, 1237.31s/it]
  9%|▉         | 2/22 [21:12<2:56:41, 530.09s/it] Computing embeddings failed after 1284.20s.
Traceback (most recent call last):
  File "scripts/mine_sequences.py", line 142, in <module>
    [job.result() for job in tqdm(jobs)]
  File "scripts/mine_sequences.py", line 142, in <listcomp>
    [job.result() for job in tqdm(jobs)]
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/submitit/core/core.py", line 266, in result
    r = self.results()
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/submitit/core/core.py", line 294, in results
    raise job_exception  # pylint: disable=raising-bad-type
submitit.core.utils.FailedJobError: Job (task=0) failed during processing with trace:
----------------------
Traceback (most recent call last):
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/utils/training.py", line 19, in wrapped_func
    return func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/utils/training.py", line 39, in wrapped_func
    return func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/utils/submitit.py", line 41, in wrapped_func
    return func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/utils/training.py", line 49, in wrapped_func
    result = func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/utils/helpers.py", line 470, in wrapped_func
    return func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/mining/nn_search.py", line 97, in compute_and_save_embeddings
    embeddings = get_embeddings(sentences)
  File "scripts/mine_sequences.py", line 95, in <lambda>
    get_embeddings = lambda sentences: get_laser_embeddings(
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/cachetools/__init__.py", line 641, in wrapper
    v = func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/utils/training.py", line 60, in wrapped_func
    return func(*args, **kwargs)
  File "/home/raphael_assis4347/muss-ptBR/muss/laser.py", line 56, in get_laser_embeddings
    encoder = get_laser_encoder(encoder_path, max_tokens=max_tokens)
  File "/home/raphael_assis4347/muss-ptBR/muss/laser.py", line 35, in get_laser_encoder
    return SentenceEncoder(encoder_path, max_sentences=None, max_tokens=max_tokens, cpu=False)
  File "/home/raphael_assis4347/muss-ptBR/resources/tools/LASER/source/embed.py", line 109, in __init__
    self.encoder.cuda()
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 689, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/home/raphael_assis4347/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 689, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

----------------------
You can check full logs with 'job.stderr(0)' and 'job.stdout(0)'or at paths:
  - /home/raphael_assis4347/muss-ptBR/experiments/submitit_logs/9513/9513_0_log.err
  - /home/raphael_assis4347/muss-ptBR/experiments/submitit_logs/9513/9513_0_log.out

 14%|█▎        | 3/22 [21:12<2:14:20, 424.21s/it]
```
And about the documentation of my experiments, I'm detailing everything in a file and I'm interested in doing a PR in the future with this information. I am very excited to contribute to this project.

**Comment by louismartin** [comment]
I see:
```
RuntimeError: CUDA error: out of memory
```
so yes it's probably due to the GPU memory.

Thanks a lot for tracking your experiments, that will be super useful on the repo, I wish I had done it as well :D

**Comment by AssisRaphael** [comment]
Hello again!

I'm returning to comment that I managed to solve the GPU out of memory issue. I followed the recommendation given in [this issue](https://github.com/facebookresearch/muss/issues/32) to reduce the number of running jobs. I have now finished the paraphrase mining step.
