### ISSUE TITLE
Error(s) in loading state_dict for BARTModel

### ISSUE THREAD

**Issue by AssisRaphael** [facebookresearch/muss#38]
Hello,
Recently I managed to train the model for Portuguese and I had problems with the size of the model dictionaries. After training, I copied the files from the folder '/muss-ptBR/experiments/submitit_logs/4085/' where the model.pt, dict.simple.txt and dict.complex.txt and the file '/resources/datasets/_c234210b2ade71918a75f34527e40d50/sentencepiece.bpe.model' and moved them to the folder 'muss-ptBR/resources/models/muss_pt_mined'. However, when running the simplification script (scripts/simplify.py) I get the following error:

```SHEEL
Traceback (most recent call last):
  File "scripts/simplify.py", line 25, in <module>
    pred_sentences = simplify_sentences(source_sentences, model_name=args.model_name)
  File "/home/raphael/muss-ptBR/muss/simplify.py", line 85, in simplify_sentences
    pred_path = simplifier(source_path)
  File "/home/raphael/muss-ptBR/muss/simplifiers.py", line 42, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File "/home/raphael/muss-ptBR/muss/simplifiers.py", line 30, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File "/home/raphael/muss-ptBR/muss/simplifiers.py", line 68, in preprocessed_simplifier
    preprocessed_pred_filepath = simplifier(preprocessed_complex_filepath)
  File "/home/raphael/muss-ptBR/muss/simplifiers.py", line 42, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File "/home/raphael/muss-ptBR/muss/simplifiers.py", line 30, in wrapped
    simplifier(complex_filepath, pred_filepath)
  File "/home/raphael/muss-ptBR/muss/simplifiers.py", line 54, in fairseq_simplifier
    fairseq_generate(complex_filepath, output_pred_filepath, exp_dir, **kwargs)
  File "/home/raphael/muss-ptBR/muss/fairseq/base.py", line 222, in fairseq_generate
    _fairseq_generate(
  File "/home/raphael/muss-ptBR/muss/utils/training.py", line 60, in wrapped_func
    return func(*args, **kwargs)
  File "/home/raphael/muss-ptBR/muss/fairseq/base.py", line 188, in _fairseq_generate
    generate.cli_main()
  File "/home/raphael/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 379, in cli_main
    main(args)
  File "/home/raphael/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 41, in main
    return _main(args, sys.stdout)
  File "/home/raphael/.local/lib/python3.8/site-packages/fairseq_cli/generate.py", line 88, in _main
    models, _model_args = checkpoint_utils.load_model_ensemble(
  File "/home/raphael/.local/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 250, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/home/raphael/.local/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 287, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/home/raphael/.local/lib/python3.8/site-packages/fairseq/models/fairseq_model.py", line 99, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/raphael/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BARTModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([5544, 1024]) from checkpoint, the shape in current model is torch.Size([5597, 1024]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([5544, 1024]) from checkpoint, the shape in current model is torch.Size([5597, 1024]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([5544, 1024]) from checkpoint, the shape in current model is torch.Size([5597, 1024]).
```

An adaptation I made in the model was to use the[ mbart50](https://github.com/facebookresearch/fairseq/tree/main/examples/multilingual#mbart50-models) instead of the mbart25. Do you know any way to resolve this error?

Thanks,

**Comment by louismartin** [comment]
Hi @AssisRaphael ,

I'm not sure where that problem comes from to be honest, it might indeed be related to mbart50. I'm a bit surprised that the vocabulary size is this small (5k?), multilingual language models are usually in the range of 250k vocab size.

I would debug by understanding where the mismatch comes from (what those weights correspond to, why 5544 and 5597) and then take a decision from that by either changing the architecture details in fairseq to match your checkpoint, or changing your checkpoint (although it might introduce random weights and break the model).
I haven't found any references of 5544 or 5597 in the fairseq repo.

**Comment by chirico85** [comment]
Hi @AssisRaphael ,
I also came across this error. But cannot really say how I solved it. I think there are many possibilities.
But first, I would give your model a name which results in True when checking `is_model_using_mbart(model_name)` 
in simplify.py. That way, you make sure that sentencepiece.bpe.model is used according to your mbart model.

If I think of anything else to solve the problem, I will get back to you.

**Comment by AssisRaphael** [comment]
Hi @louismartin  and @chirico85, thanks for the feedback.

I was training the model from an adaptation of the train_paper_model file. It seems to train two different models and the problem was occurring on the model that didn't use access. When I trained the model through the train_model file, everything went fine.
